[package]
name = "cpcli"
version = "1.0.0"
edition = "2021"

[dependencies]
reqwest = { version = "0.12.8", features = ["blocking", "rustls-tls"] }
serde = { version = "1.0.210", features = ["derive"] }
serde_json = "1.0.128"
